services:
  - type: web
    name: interview-help-backend
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8000
      - key: ENV
        value: production
      - key: ALLOWED_ORIGINS
        value: https://interview-experience-website-koqtpmwx.devinapps.com,http://localhost:4173,http://localhost:5173
      - key: GIN_MODE
        value: release
    healthCheckPath: /api/services
    autoDeploy: true
    plan: free
    region: singapore
