services:
  - type: web
    name: interview-help-backend
    env: docker
    buildCommand: docker build -t interview-help-backend .
    startCommand: docker run -p $PORT:8000 interview-help-backend
    envVars:
      - key: PORT
        value: 8000
      - key: ENV
        value: production
      - key: ALLOWED_ORIGINS
        value: https://interview-experience-website-koqtpmwx.devinapps.com
